export const FETCHING_ALERT = 'FETCHING_ALERT';
export const FETCHING_ALERT_SUCCESS = 'FETCHING_ALERT_SUCCESS';
export const FETCHING_ALERT_FAILURE = 'FETCHING_ALERT_FAILURE';

export const FETCHING_TRAFFIC = 'FETCHING_TRAFFIC';
export const FETCHING_TRAFFIC_SUCCESS = 'FETCHING_TRAFFIC_SUCCESS';
export const FETCHING_TRAFFIC_FAILURE = 'FETCHING_TRAFFIC_FAILURE';

export const FETCHING_LOCATION = 'FETCHING_LOCATION';
export const FETCHING_LOCATION_SUCCESS = 'FETCHING_LOCATION_SUCCESS';
export const FETCHING_LOCATION_FAILURE = 'FETCHING_LOCATION_FAILURE';
